services:
  price-simulator:
    container_name: price-simulator
    build:
      context: .
      dockerfile: services/price-simulator/Dockerfile
    environment: 
      - DISRUPTION_PROBABILITY=0.666 # 😈 chance that the simulator will disconnect the client
    ports:
      - "8081:8080"
    networks:
      - temporal-network

  stop-loss:
    container_name: stop-loss-server 
    build:
      context: .
      dockerfile: services/stop-loss/Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - temporal
    environment:
      - PRICE_WS_URL=ws://price-simulator:8080/prices
      - TEMPORAL_ADDRESS=temporal:7233
    networks:
      - temporal-network
    volumes: 
      - ./services/stop-loss/html:/app/html
      - ./services/stop-loss/data:/app/data
  
# -------------------
# Temporal services 👇
# from: https://github.com/temporalio/docker-compose/blob/main/docker-compose-postgres.yml
# -------------------
  postgresql: 
    container_name: temporal-postgresql 
    environment: 
     POSTGRES_PASSWORD: temporal 
     POSTGRES_USER: temporal 
    image: postgres:${POSTGRESQL_VERSION} 
    networks: 
      - temporal-network
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      - 8080:8080

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
